# Generated by Django 5.0.7 on 2024-08-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_entradas_delete_articulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='contenido',
            field=models.TimeField(max_length=500),
        ),
    ]
