# Generated by Django 5.0.7 on 2024-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_entradas_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='contenido',
            field=models.TextField(max_length=500),
        ),
    ]
