# Generated by Django 5.0.7 on 2024-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_entradas_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('mensaje', models.TextField(max_length=200)),
                ('avisos', models.BooleanField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='entradas',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='contenido',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
