# Generated by Django 5.0.7 on 2024-08-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_contacto_alter_entradas_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='avisos',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
