# Generated by Django 5.0.7 on 2024-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_entradas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
