# Generated by Django 5.0.7 on 2024-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_alter_entradas_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
