# Generated by Django 5.0.7 on 2024-09-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_alter_entradas_autor_alter_entradas_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='autor',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
