# Generated by Django 5.0.7 on 2024-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_alter_entradas_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
