# Generated by Django 5.0.7 on 2024-09-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_alter_entradas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='contenido',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='entradas',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
