# Generated by Django 5.0.7 on 2024-09-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0014_alter_entradas_autor_alter_entradas_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos'),
        ),
    ]
