# Generated by Django 5.0.7 on 2024-09-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0015_alter_entradas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos'),
        ),
    ]
