# Generated by Django 5.0.7 on 2025-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0019_entradados_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField(blank=True, max_length=2000, null=True)),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
            ],
        ),
    ]
